//! Turn `../deck-layout.json` — Phosphor's own control table, written by
//! `phosphor --deck-layout` — into the firmware's table.
//!
//! The wiring rule lives here and on the schematics, and nowhere else: the
//! shift-register inputs are assigned in table order, one per button and
//! three per encoder (push, A, B), with the sustain pedal last; pads and
//! faders take the analog multiplexers' channels in table order.

use std::fmt::Write as _;

fn main() {
    let path = "../deck-layout.json";
    println!("cargo:rerun-if-changed={path}");
    let text = std::fs::read_to_string(path).expect("firmware/deck-layout.json: run `phosphor --deck-layout > firmware/deck-layout.json`");
    let layout: serde_json::Value = serde_json::from_str(&text).expect("deck-layout.json parses");
    let channel = layout["channel"].as_u64().expect("channel") as u8;
    let controls = layout["controls"].as_array().expect("controls");

    let u8_of = |v: &serde_json::Value| v.as_u64().map(|n| n as u8);
    let mut digital = Vec::new();
    let mut encoders = Vec::new();
    let mut pads = Vec::new();
    let mut faders = Vec::new();
    let mut light_of_note = [255u8; 128];
    let mut groups: Vec<(String, Vec<u8>)> = Vec::new();
    let mut colors = Vec::new();

    for c in controls {
        let id = c["id"].as_str().expect("id");
        let kind = c["kind"].as_str().expect("kind");
        let note = u8_of(&c["note"]);
        let cc = u8_of(&c["cc"]);
        let light = u8_of(&c["light"]);
        if let (Some(n), Some(l)) = (note, light) {
            light_of_note[n as usize] = l;
        }
        let light_src = light.map_or("None".to_string(), |l| format!("Some({l})"));
        if light.is_some() {
            // Green for play, red for recording, teal for the track buttons
            // (Phosphor's selection colour), amber for everything else.
            let (r, g, b) = match id {
                "Play" => (40, 255, 90),
                "Rec" | "Overdub" => (255, 40, 30),
                _ if id.starts_with("TrackButton") => (40, 210, 190),
                _ => (255, 150, 20),
            };
            colors.push(format!("Rgb {{ r: {r}, g: {g}, b: {b} }}"));
        }
        match kind {
            "Button" => {
                digital.push(format!("Input::Button {{ note: {}, light: {light_src} }}", note.expect("button note")));
                // Buttons that pick one of a set: the set lights the last one
                // picked until Phosphor says otherwise.
                let group = ["Fn", "Mode", "Steps"].into_iter().find(|p| id.starts_with(p));
                if let (Some(group), Some(l)) = (group, light) {
                    match groups.iter_mut().find(|(g, _)| g == group) {
                        Some((_, members)) => members.push(l),
                        None => groups.push((group.to_string(), vec![l])),
                    }
                }
            }
            "Encoder" => {
                let e = encoders.len();
                encoders.push(cc.expect("encoder cc"));
                digital.push(format!("Input::Push {{ note: {} }}", note.expect("encoder note")));
                digital.push(format!("Input::EncoderA {{ encoder: {e} }}"));
                digital.push(format!("Input::EncoderB {{ encoder: {e} }}"));
            }
            "Pad" => pads.push(format!("Pad {{ note: {}, light: {} }}", note.expect("pad note"), light.expect("pad light"))),
            "Fader" => faders.push(cc.expect("fader cc")),
            other => panic!("deck-layout.json: unknown kind {other}"),
        }
    }
    digital.push("Input::Sustain".to_string());
    let lights = controls.iter().filter(|c| !c["light"].is_null()).count();

    let mut out = String::new();
    writeln!(out, "// Generated by build.rs from firmware/deck-layout.json. Do not edit.").unwrap();
    writeln!(out, "/// The deck's MIDI channel, counted from zero.").unwrap();
    writeln!(out, "pub const CHANNEL: u8 = {};", channel - 1).unwrap();
    writeln!(out, "/// Every shift-register input, in wiring order.").unwrap();
    writeln!(out, "pub const DIGITAL: [Input; {}] = [{}];", digital.len(), digital.join(", ")).unwrap();
    writeln!(out, "/// The controller number each encoder turns, in encoder order.").unwrap();
    writeln!(out, "pub const ENCODERS: [u8; {}] = {:?};", encoders.len(), encoders).unwrap();
    writeln!(out, "/// The pads, on the first multiplexer's channels 0-15.").unwrap();
    writeln!(out, "pub const PADS: [Pad; {}] = [{}];", pads.len(), pads.join(", ")).unwrap();
    writeln!(out, "/// The faders' controller numbers, on the second multiplexer's first channels.").unwrap();
    writeln!(out, "pub const FADERS: [u8; {}] = {:?};", faders.len(), faders).unwrap();
    writeln!(out, "/// How many LEDs the chain has.").unwrap();
    writeln!(out, "pub const LIGHTS: usize = {lights};").unwrap();
    writeln!(out, "/// Each LED's colour at full level, in chain order.").unwrap();
    writeln!(out, "pub const LIGHT_COLOR: [Rgb; {}] = [{}];", colors.len(), colors.join(", ")).unwrap();
    writeln!(out, "/// The LED under the control that sends each note; 255 for none.").unwrap();
    writeln!(out, "pub const LIGHT_OF_NOTE: [u8; 128] = {light_of_note:?};").unwrap();
    writeln!(out, "/// Sets of buttons of which one is chosen at a time, as LED numbers.").unwrap();
    let groups_src: Vec<String> = groups.iter().map(|(_, m)| format!("&{m:?}")).collect();
    writeln!(out, "pub const GROUPS: [&[u8]; {}] = [{}];", groups.len(), groups_src.join(", ")).unwrap();

    let dest = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("table.rs");
    std::fs::write(dest, out).unwrap();
}
